=== ATroubleshooter/MSX/DOC/UNAPI/SRC/rfc2629.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.rfc2629.org"
    xmlns="http://www.rfc2629.org"
    elementFormDefault="qualified">
  <xs:element name="abstract">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="t" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="address">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="postal" minOccurs="0" />
        <xs:element ref="phone" minOccurs="0" />
        <xs:element ref="facsimile" minOccurs="0" />
        <xs:element ref="email" minOccurs="0" />
        <xs:element ref="uri" minOccurs="0" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="annotation">
    <xs:complexType mixed="true">
      <xs:choice>
        <xs:element ref="xref" />
        <xs:element ref="eref" />
        <xs:element ref="iref" />
        <xs:element ref="cref" />
        <xs:element ref="spanx" />
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <xs:element name="appendix">
    <xs:complexType>
      <xs:choice>
        <xs:element ref="t" />
        <xs:element ref="figure" />
        <xs:element ref="texttable" />
        <xs:element ref="iref" />
        <xs:element ref="appendix" />
      </xs:choice>
      <xs:attribute name="anchor" type="xs:ID" use="optional" />
      <xs:attribute name="title" type="xs:string" use="required" />
      <xs:attribute name="toc" use="optional" default="default">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="include" />
            <xs:enumeration value="exclude" />
            <xs:enumeration value="default" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="area">
    <xs:complexType mixed="true" />
  </xs:element>

  <xs:element name="artwork">
    <xs:complexType mixed="true">
      <xs:attribute name="height" type="xs:string" use="optional" />
      <xs:attribute name="name" type="xs:string" use="optional" />
      <xs:attribute name="width" type="xs:string" use="optional" />
      <xs:attribute name="type" type="xs:string" use="optional" />
      <xs:attribute name="alt" type="xs:string" use="optional" />
      <xs:attribute name="src" type="xs:string" use="optional" />
      <xs:attribute name="align" use="optional" default="left">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="left" />
            <xs:enumeration value="center" />
            <xs:enumeration value="right" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="author">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="organization" />
        <xs:element ref="address" minOccurs="0" />
      </xs:sequence>
      <xs:attribute name="fullname" type="xs:string" use="optional" />
      <xs:attribute name="surname" type="xs:string" use="optional" />
      <xs:attribute name="initials" type="xs:string" use="optional" />
      <xs:attribute name="role" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="editor" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="back">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="references" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="section" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="c">
    <xs:complexType mixed="true">
      <xs:choice>
        <xs:element ref="xref" />
        <xs:element ref="eref" />
        <xs:element ref="iref" />
        <xs:element ref="cref" />
        <xs:element ref="spanx" />
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <xs:element name="city">
    <xs:complexType mixed="true" />
  </xs:element>

  <xs:element name="code">
    <xs:complexType mixed="true" />
  </xs:element>

  <xs:element name="country">
    <xs:complexType mixed="true" />
  </xs:element>

  <xs:element name="cref">
    <xs:complexType mixed="true">
      <xs:attribute name="anchor" type="xs:ID" use="optional" />
      <xs:attribute name="source" type="xs:string" use="optional" />
    </xs:complexType>
  </xs:element>

  <xs:element name="date">
    <xs:complexType>
      <xs:attribute name="day" type="xs:string" use="optional" />
      <xs:attribute name="year" type="xs:string" use="optional" />
      <xs:attribute name="month" type="xs:string" use="optional" />
    </xs:complexType>
  </xs:element>

  <xs:element name="email">
    <xs:complexType mixed="true" />
  </xs:element>

  <xs:element name="eref">
    <xs:complexType mixed="true">
      <xs:attribute name="target" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="facsimile">
    <xs:complexType mixed="true" />
  </xs:element>

  <xs:element name="figure">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="preamble" minOccurs="0" />
        <xs:element ref="artwork" />
        <xs:element ref="postamble" minOccurs="0" />
      </xs:sequence>
      <xs:attribute name="height" type="xs:string" use="optional" />
      <xs:attribute name="anchor" type="xs:ID" use="optional" />
      <xs:attribute name="width" type="xs:string" use="optional" />
      <xs:attribute name="alt" type="xs:string" use="optional" />
      <xs:attribute name="src" type="xs:string" use="optional" />
      <xs:attribute name="title" type="xs:string" use="optional" />
      <xs:attribute name="align" use="optional" default="left">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="left" />
            <xs:enumeration value="center" />
            <xs:enumeration value="right" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="format">
    <xs:complexType>
      <xs:attribute name="octets" type="xs:string" use="optional" />
      <xs:attribute name="type" type="xs:string" use="required" />
      <xs:attribute name="target" type="xs:string" use="optional" />
    </xs:complexType>
  </xs:element>

  <xs:element name="front">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title" />
        <xs:element ref="author" maxOccurs="unbounded" />
        <xs:element ref="date" />
        <xs:element ref="area" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="workgroup" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="keyword" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="abstract" minOccurs="0" />
        <xs:element ref="note" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="iref">
    <xs:complexType>
      <xs:attribute name="subitem" type="xs:string" use="optional" />
      <xs:attribute name="primary" use="optional" default="false">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="true" />
            <xs:enumeration value="false" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="item" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="keyword">
    <xs:complexType mixed="true" />
  </xs:element>

  <xs:element name="list">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="t" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="counter" type="xs:string" use="optional" />
      <xs:attribute name="hangIndent" type="xs:string" use="optional" />
      <xs:attribute name="style" type="xs:string" use="optional" default="empty" />
    </xs:complexType>
  </xs:element>

  <xs:element name="middle">
    <xs:complexType>
      <xs:sequence>
        <!--
        <xs:element ref="section" maxOccurs="unbounded" />
        -->
        <xs:element ref="appendix" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="section" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="note">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="t" />
      </xs:sequence>
      <xs:attribute name="title" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="organization">
    <xs:complexType mixed="true">
      <xs:attribute name="abbrev" type="xs:string" use="optional" />
    </xs:complexType>
  </xs:element>

  <xs:element name="phone">
    <xs:complexType mixed="true" />
  </xs:element>

  <xs:element name="postal">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="street" maxOccurs="unbounded" />
        <xs:choice>
          <xs:element ref="city" />
          <xs:element ref="region" />
          <xs:element ref="code" />
          <xs:element ref="country" />
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="postamble">
    <xs:complexType mixed="true">
      <xs:choice>
        <xs:element ref="xref" />
        <xs:element ref="eref" />
        <xs:element ref="iref" />
        <xs:element ref="cref" />
        <xs:element ref="spanx" />
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <xs:element name="preamble">
    <xs:complexType mixed="true">
      <xs:choice>
        <xs:element ref="xref" />
        <xs:element ref="eref" />
        <xs:element ref="iref" />
        <xs:element ref="cref" />
        <xs:element ref="spanx" />
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <xs:element name="reference">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="front" />
        <xs:element ref="seriesInfo" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="format" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="annotation" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="anchor" type="xs:ID" use="optional" />
      <xs:attribute name="target" type="xs:string" use="optional" />
    </xs:complexType>
  </xs:element>

  <xs:element name="references">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="reference" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="title" type="xs:string" use="optional" default="References" />
    </xs:complexType>
  </xs:element>

  <xs:element name="region">
    <xs:complexType mixed="true" />
  </xs:element>

  <xs:element name="rfc" xml:lang="en">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="front" />
        <xs:element ref="middle" />
        <xs:element ref="back" minOccurs="0" />
      </xs:sequence>
      <xs:attribute name="docName" type="xs:string" use="optional" />
      <xs:attribute name="iprExtract" type="xs:ID" use="optional" />
      <xs:attribute name="category" use="optional" default="info">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="std" />
            <xs:enumeration value="bcp" />
            <xs:enumeration value="info" />
            <xs:enumeration value="exp" />
            <xs:enumeration value="historic" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="obsoletes" type="xs:string" use="optional" />
      <xs:attribute name="number" type="xs:string" use="optional" />
      <xs:attribute name="seriesNo" type="xs:string" use="optional" />
      <xs:attribute name="updates" type="xs:string" use="optional" />
      <xs:attribute name="ipr" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="full2026" />
            <xs:enumeration value="noDerivativeWorks2026" />
            <xs:enumeration value="none" />
            <xs:enumeration value="full3667" />
            <xs:enumeration value="noModification3667" />
            <xs:enumeration value="noDerivatives3667" />
            <xs:enumeration value="full3978" />
            <xs:enumeration value="noModification3978" />
            <xs:enumeration value="noDerivatives3978" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="section">
    <xs:complexType>
      <xs:choice>
        <xs:element ref="t" />
        <xs:element ref="figure" />
        <xs:element ref="texttable" />
        <xs:element ref="iref" />
        <xs:element ref="section" />
      </xs:choice>
      <xs:attribute name="anchor" type="xs:ID" use="optional" />
      <xs:attribute name="title" type="xs:string" use="required" />
      <xs:attribute name="toc" use="optional" default="default">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="include" />
            <xs:enumeration value="exclude" />
            <xs:enumeration value="default" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="seriesInfo">
    <xs:complexType>
      <xs:attribute name="name" type="xs:string" use="required" />
      <xs:attribute name="value" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="spanx">
    <xs:complexType mixed="true">
      <xs:attribute name="style" type="xs:string" use="optional" default="emph" />
    </xs:complexType>
  </xs:element>

  <xs:element name="street">
    <xs:complexType mixed="true" />
  </xs:element>

  <xs:element name="t">
    <xs:complexType mixed="true">
      <xs:choice>
        <xs:element ref="list" />
        <xs:element ref="figure" />
        <xs:element ref="xref" />
        <xs:element ref="eref" />
        <xs:element ref="iref" />
        <xs:element ref="cref" />
        <xs:element ref="spanx" />
        <xs:element ref="vspace" />
      </xs:choice>
      <xs:attribute name="hangText" type="xs:string" use="optional" />
    </xs:complexType>
  </xs:element>

  <xs:element name="texttable">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="preamble" minOccurs="0" />
        <xs:element ref="ttcol" maxOccurs="unbounded" />
        <xs:element ref="c" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="postamble" minOccurs="0" />
      </xs:sequence>
      <xs:attribute name="anchor" type="xs:ID" use="optional" />
      <xs:attribute name="title" type="xs:string" use="optional" />
    </xs:complexType>
  </xs:element>

  <xs:element name="title">
    <xs:complexType mixed="true">
      <xs:attribute name="abbrev" type="xs:string" use="optional" />
    </xs:complexType>
  </xs:element>

  <xs:element name="ttcol">
    <xs:complexType mixed="true">
      <xs:attribute name="width" type="xs:string" use="optional" />
      <xs:attribute name="align" use="optional" default="left">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="left" />
            <xs:enumeration value="center" />
            <xs:enumeration value="right" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="uri">
    <xs:complexType mixed="true" />
  </xs:element>

  <xs:element name="vspace">
    <xs:complexType>
      <xs:attribute name="blankLines" type="xs:string" use="optional" default="0" />
    </xs:complexType>
  </xs:element>

  <xs:element name="workgroup">
    <xs:complexType mixed="true" />
  </xs:element>

  <xs:element name="xref">
    <xs:complexType mixed="true">
      <xs:attribute name="format" use="optional" default="default">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="counter" />
            <xs:enumeration value="title" />
            <xs:enumeration value="default" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="target" type="xs:IDREF" use="required" />
      <xs:attribute name="pageno" use="optional" default="false">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="true" />
            <xs:enumeration value="false" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== ATroubleshooter/MSX/DOC/UNAPI/SRC/unapi.xml
<?xml version="1.0"?>

<!--
<!DOCTYPE rfc SYSTEM "rfc2629.dtd">
-->

<?rfc toc="yes" ?>
<?rfc topblock="yes" ?>
<?rfc symrefs="yes" ?>
<?rfc sortrefs="yes" ?>
<?rfc compact="yes" ?>
<?rfc private="Version 1.1" ?>

<rfc xmlns="http://www.rfc2629.org"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.rfc2629.org rfc2629.xsd"
  ipr="full3978" docName="UNAPI">

	<!-- Header -->

	<front>
		<title abbrev="MSX-UNAPI">MSX-UNAPI: Unified procedure for API definition and discovery on MSX computers</title>
		<author initials="N." surname="Soriano" fullname="Nestor Soriano">
			<organization>MSX community</organization>
			<address>
				<email>konamiman@konamiman.com</email>
				<uri>http://www.konamiman.com</uri>
			</address>
		</author>
		<date month="February" year="2010" />
		<abstract>
			<t>This document describes MSX-UNAPI, a standard procedure for defining, discovering and using new APIs (Application Program Interfaces)
			for MSX computers. The goal is to provide a unified way to design and use BIOS-like software for the various kinds of new hardware that is
			being developed for these computers, altough it can be used for software-only solutions as well.</t>
		</abstract>
	</front>

	<middle>
	
		<!-- Introduction -->
	
		<section anchor="intro" title="Introduction">
			<section anchor="motivation" title="Motivation">
				<t>MSX was presented in 1983 as a standard for home computers, in the form of a set of specifications to be followed by manufacturers.
				Any brand was able to make its own model of computer; as long as the machine met the MSX standard, it was considered an MSX computer.
				This allowed for flawless interoperation between computers of different makers, something not as common at the time as it is nowadays.</t>
				
				<t>An important part of the MSX specification was the BIOS, a set of routines that -amongst other things- provided a standarized way
				to access the harwdare resources of the machine. This provided certain degree of freedom to manufacturers, which could -to some extent-
				freely choose the hardware parts that would build up their given model of MSX computer.</t>
				
				<t>Time passed and the MSX standard was discontinued by all manufacturers long time ago. However, many people still using their old MSX computers,
				and some of them even develop new hardware for these machines. Hard disk interfaces, sound cards and network cards are examples of hardware
				that has been developed for MSX computers past the commercial live of the standard.</t>
				
				<t>Altough the appearance of new hardware is of course a good thing, this causes a problem for software developers. Not having any authority
				dictating specifications for the MSX standard anymore, each hardware developer freely choses the way their hardware will have to be
				accessed from software; in other words, there are no specifications to follow at the time of designing the API (Application Program Interface)
				for the new harwdare. As a result, hardware extensions performing the same functions but being developed by different persons are software-incompatible
				(unless developers privately agree on using compatible APIs, which is not always possible).</t>
				
				<t>The intent of this document is to propose a solution for this problem:
				a standard, unified procedure for defining, discovering and using new APIs for MSX computers, aimed especially (but not exclusively)
				to the hardware development field.</t>
			</section>
			
			<section anchor="goals" title="Goals">
				<t>The main goals of this specification are:</t>
				<vspace blankLines='1' />
					<list style="symbols">
						<t>To provide a minimum set of rules to be followed by APIs that adhere to this specification. These rules are to be taken in account
						when designing (and later implementing) the various APIs. They are very simple, impose only a few restrictions on compliant code,
						and in practice allow any kind of API software to be written.</t>
						<vspace blankLines='1' />
						<t>To provide a standard procedure for discovering and using APIs that adhere to this standard and are installed
						on the MSX computer running the UNAPI aware software. This procedure is based on the MSX extended BIOS mechanism,
						and is very easy to implement and even easier to use.</t>
					</list>
			</section>
			
			<section anchor="nongoals" title="Non-goals">
				<t>It is NOT the intent of this specification, and/or is outside the scope of this document:</t>
				<vspace blankLines='1' />
					<list style="symbols">
						<t>To impose the described specification to developers or users. Altough the authors hope that the MSX-UNAPI specification
						will be useful for the MSX community, this document is merely a proposal, and adhering to it is of course optional.</t>
						<vspace blankLines='1' />
						<t>To arbiter who should desing the APIs. Common sense suggests that APIs should be designed by the first person or team that develops
						a given type of hardware (or software), but the decision of such thing is outside the scope of this document.</t>
						<vspace blankLines='1' />
						<t>To describe any API other than for illustration purposes. This documents just tells a procedure for designing APIs;
						these must be described in sepparate documents.</t> 
					</list>
			</section>
			
			<section anchor="glossary" title="Glossary">
				<t>Before proceeding any further, a glossary of terms used along this document will be introduced. It will be useful
				to understand the rules and procedures described later.</t>
				<t>MSX-UNAPI</t>
					<list style="empty"><t>Short for "MSX unified API definition and discovery standard". A set of rules to be followed when designing
					and implementing APIs, aimed mainly (but not exclusively) to hardware developers; and a procedure for discovering any such APIs available
					to application software.</t></list>
				<t>API specification</t>
					<list style="empty"><t>API stands for "Application Program Interface". The description of a set of routines that perform some action
					(which usually, but not necessarily, involve accessing some kind of hardware), including the precise description
					of input and output parameters, as well as the side effects caused by the execution of each routine.</t></list>
				<t>UNAPI compliant API specification</t>
					<list style="empty"><t>An API specification that conforms to the rules for API specifications described in this document.</t></list>
				<t>API specification identifier</t>
					<list style="empty"><t>An alphanumeric, case-insensitive string made of up to 15 characters, which uniquely identifies an UNAPI compliant
					API specification. For example the identifier of an API specification for Ethernet cards could be "ETHERNET". See <xref target="apirule1" />
					for more details.</t></list>
				<t>The XXXXX UNAPI specification</t>
					<list style="empty"><t>The specification for an UNAPI compliant API whose specification identifier is XXXXX.
					For example, "the Ethernet UNAPI specification".</t></list>
				<t>XXXXX UNAPI compliant API implementation</t>
					<list style="empty"><t>Real code that builds up a set of routines which conforms to an UNAPI compliant API specification (and more
					precisely, to the XXXXX UNAPI specification). There may be several implementations of one single specification, each made by a
					different person or team; but if they strictly conform to the API specification, they are indistinguishable with respect to usage
					and behavior.</t></list>
				<t>API implementation name</t>
					<list style="empty"><t>An alphanumeric string made of up to 63 characters, which uniquely identifies an API implementation.
					For example the name of an implementation of the Ethernet UNAPI could be "ObsoNET", while the name of
					other implementation could be "UltraNET Supercard". See <xref target="apirule5" /> for more details.</t></list>
				<t>XXXXX UNAPI client software</t>
					<list style="empty"><t>Application software that invokes the routines of an XXXXX UNAPI compliant API implementation.
					For example, a TCP/IP stack could act as client software of the Ethernet UNAPI. The client software must use
					the discovery procedure (see <xref target="discovery" />) to locate the available API implementations, and usually it does not matter which
					one is used if more than one is found.</t></list>
        <t>Specificationless UNAPI application</t>
        <list style="empty">
          <t>
            Application software (typically, a resident application) that does not conform to any concrete UNAPI specification,
            but that make use of the remaining of the UNAPI infrastructure, namely, the implementation and discovery rules.
            See <xref target="specless" /> for more details.
        </t>
        </list>
        <t>#FF</t>
					<list style="empty"><t>Character # is used in this document as a prefix for hexadecimal numbers, so for example #FF is 255.</t></list>
				<t>Through this document, and unless otherwise stated, the term "API specification" will actually have the meaning of "UNAPI compliant API specification".
				The same applies to references to API implementations.</t>
			</section>
			
			<section anchor="samplescenario" title="Sample scenario">
				<t>This section provides an fictional scenary that briefly shows the steps that are needed in order to design and implement UNAPI compliant APIs.
				The goal is to provide the reader a basic understanding about how all the whole thing works, so that it is easier to read
				the detailed rules and procedures that are provided in the remaining of the document.</t>
